---
# defaults file for moodle
cr_group: m4e.krestomat.io
cr_kind: Moodle

# custom resource state: present, absent, suspended, inmaintenance
cr_state: present

meta_name_max_length: 26

# templates
moodle_config_template: moodle/config.php.j2
moodle_muc_config_template: moodle/muc-config.json.j2
moodle_script_muc_config_template: moodle/muc-config.php.j2
moodle_instance_template: moodle/moodle-instance.j2
moodle_script_status_template: moodle/status.php.j2
moodle_deploy_spec_template: deploy/moodle-spec.yaml.j2
moodle_new_instance_job_spec_template: job/moodle-new-instance-spec.yaml.j2
moodle_update_job_spec_template: job/moodle-update-spec.yaml.j2
moodle_cronjob_spec_template: cronjob/moodle-spec.yaml.j2

# common labels
meta_app_created_by: moodle-operator
